export const ZOOM_MAX = 10;
export const FINAL_SPACE = 34;
export const X_SNAP_TO = 1;

export const BASE_DIV_WIDTH = 1064.32;
export const BASE_TIME_INDICATOR_MARGIN = 10.5;
export const INITIAL_NUMBER_OF_MAIN_TIME_INDICATOR = 10;
export const INITIAL_NUMBER_OF_SUB_TIME_INDICATOR = 90;
export const INITIAL_TOTAL_NUMBER_OF_INDICATORS =
	INITIAL_NUMBER_OF_MAIN_TIME_INDICATOR * INITIAL_NUMBER_OF_SUB_TIME_INDICATOR;
